INSERT INTO FLAFEL (ID , NAME , HAS_SALAD, HAS_TEHENA, WEIGHT) VALUES (1 , 'SMALL' , 1, 1, 50);
INSERT INTO FLAFEL (ID , NAME , HAS_SALAD, HAS_TEHENA, WEIGHT) VALUES (2 , 'Medium' , 1, 1, 70);
INSERT INTO FLAFEL (ID , NAME , HAS_SALAD, HAS_TEHENA, WEIGHT) VALUES (3 , 'BIG' , 1, 1, 120);
